In [350]:
import numpy as np
import re
#with open('Day04.example','r') as f:
with open('Day04.input','r') as f:
    rawdata = f.read().splitlines()

cards = []
ncards = 0
tmp = []
for idx, line in enumerate(rawdata):
    if idx == 0:
        bingo = [int(i) for i in line.split(',')]
    elif line == '':
        if idx == 1:
            continue
        else:
            cards.append(tmp)
            tmp = []
            continue
    else:
        row = [int(i) for i in re.split(' +',line.strip())]
        if not len(tmp): # First row
            tmp = np.array(row)
        else:
            tmp = np.vstack([tmp,row])

cards.append(tmp)

def check(card, pos):
    if np.isnan(card[:,pos[1]]).all(): 
        return True
    elif np.isnan(card[pos[0],:]).all():
        return True
    else:
        return False

def punch(card, pos):
    card = card.astype('float')
    card[pos[0],pos[1]] = np.nan
    return card

In [344]:
for ball in bingo:
    for cardx, card in enumerate(cards):
        for rdx, row in enumerate(card):
            for cdx, value in enumerate(row):
                if value == ball:
                    print('VALUE: {}'.format(value)) 
                    card = punch(card,[rdx,cdx])
                    cards[cardx] = card
                if check(card, [rdx, cdx]):
                    print('WINNER!')
                    print('Ball: {}'.format(ball))
                    print('Card#: {}'.format(cardx))
                    print('CARD: {}'.format(card))
                    break
            else:
                continue
            break
        else:
            continue
        break
    else:
        continue
    break



VALUE: 7
VALUE: 7
VALUE: 7
VALUE: 4.0
VALUE: 4.0
VALUE: 4.0
VALUE: 9.0
VALUE: 9.0
VALUE: 9.0
VALUE: 5.0
VALUE: 5.0
VALUE: 5.0
VALUE: 11.0
VALUE: 11.0
VALUE: 11.0
VALUE: 17.0
VALUE: 17.0
VALUE: 17.0
VALUE: 23.0
VALUE: 23.0
VALUE: 23.0
VALUE: 2.0
VALUE: 2.0
VALUE: 2.0
VALUE: 0.0
VALUE: 0.0
VALUE: 0.0
VALUE: 14.0
VALUE: 14.0
VALUE: 14.0
VALUE: 21.0
VALUE: 21.0
VALUE: 21.0
VALUE: 24.0
VALUE: 24.0
VALUE: 24.0
WINNER!
Ball: 24
Card#: 2
CARD: [[nan nan nan nan nan]
 [10. 16. 15. nan 19.]
 [18.  8. nan 26. 20.]
 [22. nan 13.  6. nan]
 [nan nan 12.  3. nan]]


In [288]:
np.nansum(cards[38]) * 75

65325.0

# PART TWO

In [331]:
for c in cards:
    print(c)

[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]


In [297]:
a = [11,22,33,44]
a.pop(1)
a

[11, 33, 44]

In [310]:
def runit():
    for ball in bingo:
        for cardx, card in enumerate(cards):
            for rdx, row in enumerate(card):
                for cdx, value in enumerate(row):
                    if value == ball:
                        #print('VALUE: {}'.format(value)) 
                        card = punch(card,[rdx,cdx])
                        cards[cardx] = card
                    if check(card, [rdx, cdx]):
                        #print('WINNER!')
                        #print('Ball: {}'.format(ball))
                        #print('Card#: {}'.format(cardx))
                        #print('CARD: {}'.format(card))
                        return[ball, cardx]


In [319]:
print('Answer to part one: {}'.format(np.nansum(cards[b])*a))

Answer to part one: 4512.0


In [351]:
winnerCards = []
allcards = [i for i in range(len(cards))]
while True:
    if len(cards) == 1:
        break
    else:
        [a,b] = runit()
        #print('winner card: {}'.format(b))
        winnerCards.append(b)
        cards.pop(b)
# One last round to win
[a,b] = runit()
print('Answer to part two: {}'.format(np.nansum(cards[0]*a)))

Answer to part two: 4624.0


In [341]:
allcards

[0, 1, 2]

In [327]:
winnerCards

[2, 0]